# Generated by Django 5.1.4 on 2025-04-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='pokemon',
            new_name='movie',
        ),
    ]
