# Generated by Django 5.1.6 on 2025-04-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_pokemon_item_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='movie',
            new_name='pokemon',
        ),
    ]
