# Generated by Django 5.1.4 on 2025-04-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_alter_pokemon_image_alter_pokemon_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
