# Generated by Django 5.1.4 on 2025-04-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0005_alter_pokemon_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
